# Interacting with the Mosqlimate datastore
[ðŸ“¥ Download Notebook](https://github.com/Mosqlimate-project/mosqlimate-client/blob/main/docs/tutorials/API/datastore.ipynb)

Fetching data from the Mosqlimate API. Below, you can find example code to pull data from both the `Infodengue` and `Climate` datasets.

In [1]:
import os
from dotenv import load_dotenv
load_dotenv()

api_key = os.getenv("API_KEY")

In [2]:
import mosqlient

## InfoDengue

In [3]:
mosqlient.get_infodengue?

Signature:
mosqlient.get_infodengue(
    api_key: str,
    disease: Literal['dengue', 'zika', 'chikungunya'],
    start_date: datetime.date | str,
    end_date: datetime.date | str,
    uf: Optional[Literal['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO', 'DF']] = None,
    geocode: Optional[int] = None,
) -> pandas.core.frame.DataFrame
Docstring: <no docstring>
File:      ~/Projetos/Mosqlimate/mosqlimate-client/mosqlient/datastore/_infodengue_get_impl.py
Type:      function

In [4]:
mosqlient.get_infodengue(
    api_key = api_key,
    disease =  "dengue",
    start_date = "2022-01-01",
    end_date = "2023-01-01",
    geocode = 4108304
).head()

,data_iniSE,SE,casos_est,casos_est_min,casos_est_max,casos,municipio_geocodigo,p_rt1,p_inc100k,Localidade_id,...,nivel_inc,umidmed,umidmin,tempmed,tempmax,casprov,casprov_est,casprov_est_min,casprov_est_max,casconf
0,2023-01-01,202301,201.0,201,201,201,4108304,0.061934,77.832160,0,...,1,71.853471,46.801500,24.708333,30.285714,71,None,None,None,None
1,2022-12-25,202252,198.0,198,198,198,4108304,0.000130,76.670490,0,...,1,77.304920,57.647072,23.315657,27.666667,160,None,None,None,None
2,2022-12-18,202251,205.0,205,205,205,4108304,0.000004,79.381060,0,...,1,83.517000,65.056448,22.354167,27.000000,194,None,None,None,None
3,2022-12-11,202250,320.0,320,320,320,4108304,0.392965,123.911896,0,...,1,75.229822,44.587868,25.094697,31.000000,309,None,None,None,None
4,2022-12-04,202249,289.0,289,289,289,4108304,0.018038,111.907936,0,...,1,76.458244,54.574316,27.239177,32.857143,266,None,None,None,None

To get the data for all the cities in a state, don't fill the `geocode` field, as in the example below:

In [5]:
mosqlient.get_infodengue(
    api_key = api_key,
    disease =  "dengue",
    start_date = "2022-01-01",
    end_date = "2023-01-01", 
    uf = 'AL'
).head()

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 18/18 [00:02<00:00,  7.61requests/s]

,data_iniSE,SE,casos_est,casos_est_min,casos_est_max,casos,municipio_geocodigo,p_rt1,p_inc100k,Localidade_id,...,nivel_inc,umidmed,umidmin,tempmed,tempmax,casprov,casprov_est,casprov_est_min,casprov_est_max,casconf
0,2023-01-01,202301,0.0,0,0,0,2703700,0.0,0.0,0,...,0,83.854557,60.179396,25.375,29.857143,0,None,None,None,None
1,2023-01-01,202301,0.0,0,0,0,2700102,0.0,0.0,0,...,0,83.854557,60.179396,25.375,29.857143,0,None,None,None,None
2,2023-01-01,202301,0.0,0,0,0,2702504,0.0,0.0,0,...,0,83.854557,60.179396,25.375,29.857143,0,None,None,None,None
3,2023-01-01,202301,0.0,0,0,0,2709202,0.0,0.0,0,...,0,83.854557,60.179396,25.375,29.857143,0,None,None,None,None
4,2023-01-01,202301,0.0,0,0,0,2709152,0.0,0.0,0,...,0,83.854557,60.179396,25.375,29.857143,0,None,None,None,None

## Climate

In [6]:
mosqlient.get_climate?

Signature:
mosqlient.get_climate(
    api_key: str,
    start_date: datetime.date | str,
    end_date: datetime.date | str,
    uf: Optional[Literal['AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO', 'DF']] = None,
    geocode: Optional[int] = None,
) -> pandas.core.frame.DataFrame
Docstring: <no docstring>
File:      ~/Projetos/Mosqlimate/mosqlimate-client/mosqlient/datastore/_climate_get_impl.py
Type:      function

In [7]:
mosqlient.get_climate(
    api_key = api_key,
    start_date = "2022-01-01",
    end_date = "2022-01-01", 
    uf = "RJ",
).head()

,date,geocodigo,epiweek,temp_min,temp_med,temp_max,precip_min,precip_med,precip_max,precip_tot,pressao_min,pressao_med,pressao_max,umid_min,umid_med,umid_max
0,2022-01-01,3304904,202152,22.6257,24.3860,27.0321,3.6204,11.1975,13.9251,89.5801,0.9792,0.9809,0.9822,73.2068,88.1539,96.0204
1,2022-01-01,3300456,202152,22.0534,24.4950,28.0489,2.9373,10.3552,16.4463,82.8420,0.9841,0.9856,0.9871,71.4547,86.2787,95.7525
2,2022-01-01,3306305,202152,19.7466,22.2258,25.2781,0.7202,6.7313,19.1833,53.8505,0.9383,0.9399,0.9413,66.3477,80.9101,91.8641
3,2022-01-01,3302502,202152,21.2800,23.3756,26.6641,2.5879,9.6577,14.7341,77.2612,0.9632,0.9648,0.9660,72.5174,88.8297,96.9553
4,2022-01-01,3303203,202152,21.8972,24.2891,27.5884,3.5619,11.4151,18.2473,91.3207,0.9773,0.9789,0.9804,72.5641,85.7219,95.6470

In [8]:
mosqlient.get_climate(
    api_key = api_key,
    start_date = "2022-01-01",
    end_date = "2023-01-01", 
    geocode = 4108304,
)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1/1 [00:00<00:00,  2.16requests/s]

,date,geocodigo,epiweek,temp_min,temp_med,temp_max,precip_min,precip_med,precip_max,precip_tot,pressao_min,pressao_med,pressao_max,umid_min,umid_med,umid_max
0,2022-01-01,4108304,202152,23.6794,29.6633,35.3228,0.0000,0.0132,0.0978,0.1058,0.9624,0.9652,0.9681,30.1244,52.8195,80.1019
1,2022-01-02,4108304,202201,25.9288,31.0351,36.3261,0.0000,0.0043,0.0220,0.0345,0.9641,0.9662,0.9685,31.7948,48.0208,67.4433
2,2022-01-03,4108304,202201,26.2168,30.1859,34.8287,0.0000,0.1443,0.6431,1.1544,0.9657,0.9673,0.9696,40.3521,56.3396,75.7326
3,2022-01-04,4108304,202201,24.9282,27.3683,29.5687,0.0028,5.3999,15.2487,43.1995,0.9622,0.9646,0.9664,61.2906,76.2920,86.0319
4,2022-01-05,4108304,202201,24.5059,27.6275,31.2310,0.0000,2.2207,15.3052,17.7653,0.9639,0.9648,0.9663,51.0381,74.0777,93.2987
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2022-12-28,4108304,202252,21.7809,25.4237,30.3080,0.0990,0.9195,1.7668,7.3559,0.9679,0.9696,0.9714,42.2631,74.1699,94.4107
362,2022-12-29,4108304,202252,18.9820,25.8130,32.4540,0.0000,0.2209,1.7668,1.7668,0.9705,0.9725,0.9747,29.4484,53.9913,81.7848
363,2022-12-30,4108304,202252,20.5351,27.1068,33.5379,0.0000,0.0001,0.0004,0.0004,0.9689,0.9721,0.9741,29.4692,53.4310,80.9801
364,2022-12-31,4108304,202252,23.5194,28.8650,34.5015,0.0000,0.0182,0.0493,0.1457,0.9685,0.9714,0.9741,35.0052,53.6517,73.5915
365,2023-01-01,4108304,202301,25.5737,30.1169,35.1959,0.0002,0.0817,0.3001,0.6539,0.9664,0.9701,0.9725,38.9653,57.2024,75.5044